version: '3'

services:
  app:
    build:
      context: .
    user: root
    ports:
      - '8888:8888'
    environment:
      - GRANT_SUDO=yes
      - QUARTO_PYTHON=/opt/conda/bin/python
    platform: linux/amd64
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}
        target: /home/jovyan/work
    command: sleep infinity
